[tool.poetry]
name = "favie-api-schema"
version = "0.1.65"
description = ""
authors = ["tim <tim@srp.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "2.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
